sudo: required
services: 
  - docker

before_install:
  - docker build -t zhafa467/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true zhafa467/react-test npm test

after_success:
  - docker build -t zhafa467/multi-client ./client
  - docker build -t zhafa467/multi-nginx ./nginx
  - docker build -t zhafa467/multi-server ./server
  - docker build -t zhafa467/multi-worker ./worker
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images to push to Docker hub
  - docker push zhafa467/multi-client
  - docker push zhafa467/multi-nginx
  - docker push zhafa467/multi-server
  - docker push zhafa467/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'southeast-2'
  app: 'Multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-476290624158'
  bucket_path: 'docker-multi'
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
